guidance_node:
  ros__parameters:
    sides: 4
    length: 0.5
    wheel_relation: 1.0
    KP: 0.1
    KI: 0.05
    KD: 0.001
    u_max: 1.
    u_min: -1.
state_estimate:
  ros__parameters:
    wheel_relation2: 1.0
    angle_ponder: 1.0