guidance_node:
  ros__parameters:
    sides: 4
    length: 0.5
    wheel_relation: 1.0
    KP: 1.0
    KI: 0.1
    KD: 0.1
    u_max: 0.5
    u_min: -0.5
state_estimate:
  ros__parameters:
    wheel_relation2: 1.0
    angle_ponder: 1.0